name: Build LaTeX Resume

on:
  push:
    paths:
      - 'resume.tex'
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: xu-cheng/latex-action@v2
      with:
        root_file: resume.tex
    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: resume
        path: resume.pdf
